//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Category
{
    public Category()
    {
        this.Products = new HashSet<Product>();
    }

    public int Category_Id { get; set; }
    public string CategoryName { get; set; }
    public string Model { get; set; }
    public string Available { get; set; }

    public virtual ICollection<Product> Products { get; set; }
}

public partial class Customer
{
    public Customer()
    {
        this.Orders = new HashSet<Order>();
    }

    public int Customer_Id { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string E_mail { get; set; }
    public string ContactNumber { get; set; }
    public string SecurityQuestion { get; set; }
    public string SecurityAnswer { get; set; }

    public virtual ICollection<Order> Orders { get; set; }
}

public partial class Employee
{
    public Employee()
    {
        this.Orders = new HashSet<Order>();
    }

    public int Employee_Id { get; set; }
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string LastName { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Role { get; set; }
    public string SecuritryQuestion { get; set; }
    public string SecuritAnswer { get; set; }

    public virtual ICollection<Order> Orders { get; set; }
}

public partial class Order
{
    public Order()
    {
        this.OrderDeatails = new HashSet<OrderDeatail>();
    }

    public int Order_Id { get; set; }
    public Nullable<int> OrderNO { get; set; }
    public System.DateTime OrderDate { get; set; }
    public Nullable<int> Customer_Id { get; set; }
    public Nullable<int> Employee_Id { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual Employee Employee { get; set; }
    public virtual ICollection<OrderDeatail> OrderDeatails { get; set; }
}

public partial class OrderDeatail
{
    public int OrderDeatil_Id { get; set; }
    public Nullable<int> Order_Id { get; set; }
    public string DeatilsBody { get; set; }
    public Nullable<int> Product_Id { get; set; }
    public Nullable<System.DateTime> OrderDeatailsDate { get; set; }
    public Nullable<decimal> OrderDeatailsPrice { get; set; }

    public virtual Order Order { get; set; }
    public virtual Product Product { get; set; }
}

public partial class Product
{
    public Product()
    {
        this.OrderDeatails = new HashSet<OrderDeatail>();
    }

    public int Product_Id { get; set; }
    public string ProductName { get; set; }
    public Nullable<int> ProductNO { get; set; }
    public Nullable<decimal> ProductPrice { get; set; }
    public Nullable<int> Category_Id { get; set; }

    public virtual Category Category { get; set; }
    public virtual ICollection<OrderDeatail> OrderDeatails { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Show_Customer_Order_Result
{
    public int Order_Id { get; set; }
    public Nullable<int> OrderNO { get; set; }
    public System.DateTime OrderDate { get; set; }
    public string DeatilsBody { get; set; }
    public Nullable<System.DateTime> OrderDeatailsDate { get; set; }
    public Nullable<decimal> OrderDeatailsPrice { get; set; }
    public string ProductName { get; set; }
    public Nullable<int> ProductNO { get; set; }
    public Nullable<decimal> ProductPrice { get; set; }
    public string CategoryName { get; set; }
    public string Model { get; set; }
    public string Available { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
